# Generated by Django 5.1.1 on 2025-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_alter_expense_category_alter_expense_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
    ]
