# Generated by Django 5.1.1 on 2025-07-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0004_expense_bill_file_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Medical', 'Medical'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('NetBanking', 'NetBanking')], max_length=50),
        ),
    ]
